### ISSUE TITLE
features for Hollywood Extended?

### ISSUE THREAD

**Issue by cmhungsteve** [alexanderrichard/NeuralNetwork-Viterbi#4]
Hello,

Can you also provide the extracted features for the Hollywood Extended dataset as you did for the other two datasets?

Thank you.

**Comment by alexanderrichard** [comment]
Hi! Unfortunately, I don't have the Hollywood Ext features at hand. You may contact one of my former colleagues who co-authored the paper to provide you with the dataset. They might be able to help.

**Comment by cmhungsteve** [comment]
got it. Thank you.
