### ISSUE TITLE
Size mis-match errors

### ISSUE THREAD

**Issue by ChinaYi** [alexanderrichard/NeuralNetwork-Viterbi#8]
Hi

**Comment by ChinaYi** [comment]
I meet an error when I run the code.

read data...
done
Traceback (most recent call last):
  File "train.py", line 40, in <module>
    loss = trainer.train(sequence, transcript, batch_size = 512, learning_rate = learning_rate)
  File "/home/yi/eclipse-workspace/NeuralNetwork-Viterbi-master/utils/network.py", line 185, in train
    log_probs = self._forward(data_wrapper) - np.log(self.prior)
  File "/home/yi/eclipse-workspace/NeuralNetwork-Viterbi-master/utils/network.py", line 133, in _forward
    log_probs[offset : offset + output.shape[1], :] = output.data.cpu()
ValueError: could not broadcast input array from shape (512,1,48) into shape (1,48)

It seems that the size of 'log_probs' does not match the size of 'output'. Anyone has the same problem?

**Comment by alexanderrichard** [comment]
Hey! Yes, I recently changed the code and that introduced the error. I'm in the middle of a move right now and did not yet find time to fix it, sorry for the inconvenience.

The solution proposed here https://github.com/alexanderrichard/NeuralNetwork-Viterbi/issues/5 will work (pretty much at the end of the thread).

Again, sorry for the inconvenience.
